name: Laravel Workflow

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: hotel_booking_system
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping -h 127.0.0.1 --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      # .envファイルの存在を確認
      - name: Verify .env file
        run: |
          if [ ! -f ".env" ]; then
            echo ".env file not found"
            exit 1
          fi

      # .envファイルの内容を環境変数としてエクスポート
      - name: Set environment variables from .env
        run: |
          set -o allexport
          source .env
          set +o allexport

      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate key
        run: php artisan key:generate

      - name: Set Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Run Laravel Pint
        run: ./vendor/bin/pint --test

      - name: Security check
        run: composer audit

      - name: Debug information
        if: failure()
        run: |
          php --version
          composer --version
          php artisan --version
          cat .env
          ls -la
          cat storage/logs/laravel.log

      - name: Run database migrations
        run: php artisan migrate --force

  # deploy:
  #   needs: laravel-tests
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Setup PHP
  #       uses: shivammathur/setup-php@v2
  #       with:
  #         php-version: "8.2"

  #     - name: Install Dependencies
  #       run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

  #     - name: Deploy with Laravel Workflow
  #       run: php artisan workflow:deploy
  #       env:
  #         WORKFLOW_ENABLED: true
  #         DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
  #         DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
  #         DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
